import { db, pathwayItemsTable, activitiesTable, curriculumLinksTable } from "@workspace/db";
import { sql, isNull, eq, and } from "drizzle-orm";
import { logger } from "./logger";

export async function seedIfEmpty(): Promise<void> {
  const [{ count: pathwayCount }] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(pathwayItemsTable);

  if (pathwayCount === 0) {
    await db.insert(pathwayItemsTable).values(DEFAULT_PATHWAY_ITEMS);
    logger.info({ inserted: DEFAULT_PATHWAY_ITEMS.length }, "Seeded pathway items");
  }

  // Activities: additive seeding so newly-added defaults (e.g. Mr Meehl video links)
  // are inserted on subsequent boots without duplicating existing default rows.
  const ALL_DEFAULTS = [...DEFAULT_ACTIVITIES, ...MEEHL_ACTIVITIES];
  const existing = await db
    .select({ title: activitiesTable.title })
    .from(activitiesTable)
    .where(isNull(activitiesTable.teacherId));
  const existingTitles = new Set(existing.map((r) => r.title));
  const toInsert = ALL_DEFAULTS.filter((a) => !existingTitles.has(a.title));
  if (toInsert.length > 0) {
    await db.insert(activitiesTable).values(toInsert);
    logger.info({ inserted: toInsert.length }, "Seeded missing default activities");
  }

  // Backfill youtubeLink on existing default rows whose link is still empty.
  const linkUpdates = ALL_DEFAULTS.filter((a) => a.youtubeLink && existingTitles.has(a.title));
  for (const a of linkUpdates) {
    await db
      .update(activitiesTable)
      .set({ youtubeLink: a.youtubeLink })
      .where(and(
        eq(activitiesTable.title, a.title),
        isNull(activitiesTable.teacherId),
        eq(activitiesTable.youtubeLink, ""),
      ));
  }

  const [{ count: curCount }] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(curriculumLinksTable);
  if (curCount === 0) {
    await db.insert(curriculumLinksTable).values(DEFAULT_CURRICULUM_LINKS);
    logger.info({ inserted: DEFAULT_CURRICULUM_LINKS.length }, "Seeded curriculum links");
  }
}

const KEY_STAGES = ["EYFS", "KS1", "KS2", "KS3", "KS4"] as const;

const STRAND_PROGRESSIONS: Record<string, Record<string, string[]>> = {
  Rhythm: {
    EYFS: ["Steady pulse through clapping and movement", "Fast vs slow contrast", "Long and short sounds"],
    KS1: ["Beat vs rhythm", "ta and ti-ti", "Simple 4-beat patterns", "Rest (z)"],
    KS2: ["tika-tika (semiquavers)", "syncopa", "dotted crotchet patterns", "6/8 compound time intro"],
    KS3: ["Dotted rhythms in context", "Compound time 6/8 and 9/8", "Cross-rhythms", "Rhythm dictation 8 beats"],
    KS4: ["Irregular metres 5/4 and 7/8", "Complex polyrhythms", "Notational fluency for composition"],
  },
  Solfa: {
    EYFS: ["Two-note chants (so-mi)", "Echo singing", "High vs low pitch awareness"],
    KS1: ["so-mi-la patterns", "Adding do (low)", "Pentatonic do-re-mi-so-la"],
    KS2: ["Adding fa and ti (full diatonic)", "Major scale singing", "Simple two-part rounds"],
    KS3: ["Modes (Dorian, Mixolydian)", "Chromatic passing notes", "Minor scales (natural, harmonic)"],
    KS4: ["Modulation by ear", "Chromaticism in melody", "Tonic solfa for analysis"],
  },
  "Inner Hearing": {
    EYFS: ["Silent verses in songs", "Hidden words games"],
    KS1: ["Sing in head, out loud alternation"],
    KS2: ["Inner hearing of pitch patterns"],
    KS3: ["Silent reading of melodic phrases"],
    KS4: ["Audiation of full phrases for composition"],
  },
  "Aural Skills": {
    EYFS: ["Recognise loud/quiet, fast/slow"],
    KS1: ["Identify high/low, same/different"],
    KS2: ["Identify rhythmic and melodic patterns"],
    KS3: ["Identify intervals (3rd, 5th, octave)"],
    KS4: ["Identify chords I, IV, V; cadences"],
  },
  "Singing Games": {
    EYFS: ["Bee Bee Bumblebee", "Bow Wow Wow", "Ring around the rosy"],
    KS1: ["Bounce High Bounce Low", "Lucy Locket", "Apple Tree"],
    KS2: ["Old Brass Wagon", "Frog in the Meadow", "Cumberland Gap"],
    KS3: ["Folk songs as part-singing material"],
    KS4: ["Folk repertoire for analysis"],
  },
  "Hand Signs": {
    EYFS: ["so-mi gestures"],
    KS1: ["do, re, mi, so, la"],
    KS2: ["Full diatonic hand signs"],
    KS3: ["Hand signs with chromatic alterations"],
    KS4: ["Hand signs supporting modulation"],
  },
  "Rhythm Dictation": {
    EYFS: ["Echo clap 2-beat"],
    KS1: ["Notate 4-beat ta/ti-ti"],
    KS2: ["Notate 8-beat with rests and tika-tika"],
    KS3: ["Notate 8-beat with syncopa and dotted"],
    KS4: ["Notate 16-beat with compound time"],
  },
  "Melodic Dictation": {
    EYFS: ["High/low matching"],
    KS1: ["so-mi-la dictation"],
    KS2: ["Pentatonic dictation"],
    KS3: ["Diatonic dictation"],
    KS4: ["Modulation and chromatic dictation"],
  },
  "Improvisation": {
    EYFS: ["Make up sounds on classroom instruments"],
    KS1: ["so-mi question and answer"],
    KS2: ["Pentatonic improvisation"],
    KS3: ["Diatonic and modal improvisation"],
    KS4: ["Improvise over chord changes"],
  },
  "Composition": {
    EYFS: ["Sound stories"],
    KS1: ["Compose 4-beat rhythms"],
    KS2: ["Compose pentatonic melodies"],
    KS3: ["Compose two-part textures"],
    KS4: ["Compose with form: ABA, theme and variation"],
  },
  "Part Work": {
    EYFS: ["Group call-and-response"],
    KS1: ["Ostinato accompaniment"],
    KS2: ["Two-part rounds and canons"],
    KS3: ["Three-part part-singing"],
    KS4: ["Four-part part-singing and SATB analysis"],
  },
};

const DEFAULT_PATHWAY_ITEMS = (() => {
  const items: Array<{
    keyStage: string;
    yearGroup: string;
    strand: string;
    title: string;
    description: string;
    sequenceOrder: number;
    isCustom: number;
  }> = [];
  let order = 0;
  for (const ks of KEY_STAGES) {
    for (const [strand, byKs] of Object.entries(STRAND_PROGRESSIONS)) {
      const titles = byKs[ks];
      if (!titles) continue;
      for (const title of titles) {
        items.push({
          keyStage: ks,
          yearGroup: defaultYearGroup(ks),
          strand,
          title,
          description: `Default Kodály progression step for ${strand} at ${ks}.`,
          sequenceOrder: order++,
          isCustom: 0,
        });
      }
    }
  }
  return items;
})();

function defaultYearGroup(ks: string): string {
  switch (ks) {
    case "EYFS": return "Reception";
    case "KS1": return "Year 1-2";
    case "KS2": return "Year 3-6";
    case "KS3": return "Year 7-9";
    case "KS4": return "Year 10-11";
    default: return "";
  }
}

const DEFAULT_ACTIVITIES = [
  {
    title: "Bee Bee Bumblebee",
    ageRange: "4-6",
    keyStage: "EYFS",
    kodalyFocus: "Steady pulse, so-mi",
    rhythmElement: "ta, ti-ti",
    solfaElement: "so-mi",
    curriculumLink: "EYFS EAD: Being Imaginative and Expressive",
    description: "Classic singing game introducing steady pulse and the so-mi interval.",
    instructions: "Sit in a circle. Sing 'Bee bee bumblebee, sting a person on the knee, sting a pig upon the snout, you are out!' Tap pulse on knees. On 'out', the child pointed to leaves the circle.",
    questions: "Where is the steady beat? Are these notes high or low?",
    assessmentFocus: "Pulse keeping; pitch matching of so and mi.",
    requiredResources: "None — singing game only.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Singing Game",
    difficulty: "Beginner",
    term: "Autumn 1",
    tags: ["pulse", "so-mi", "circle game"],
  },
  {
    title: "Apple Tree (so-mi-la)",
    ageRange: "5-7",
    keyStage: "KS1",
    kodalyFocus: "so-mi-la",
    rhythmElement: "ta, ti-ti",
    solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Use voices expressively, sing songs and chants",
    description: "Singing game adding la above so for new pitch contrast.",
    instructions: "Two children form an arch. Class walks under singing. Whoever is caught at 'OUT' joins the arch.",
    questions: "Which note is highest? Can you show me with hand signs?",
    assessmentFocus: "Three-note pitch matching; hand sign accuracy.",
    requiredResources: "Open space.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Singing Game",
    difficulty: "Beginner",
    term: "Autumn 2",
    tags: ["so-mi-la", "hand signs"],
  },
  {
    title: "Rhythm Flashcard Round",
    ageRange: "6-8",
    keyStage: "KS1",
    kodalyFocus: "ta and ti-ti",
    rhythmElement: "ta, ti-ti, rest",
    solfaElement: "",
    curriculumLink: "NC Music KS1: Play tuned and untuned instruments musically",
    description: "Show 4-beat flashcards; class claps and says rhythm names.",
    instructions: "Hold up a 4-beat card. Class claps in pulse and says 'ta, ti-ti, ta, rest'. Rotate cards. Add new patterns each lesson.",
    questions: "How many sounds on beat 2? What is the rhythm name?",
    assessmentFocus: "Rhythm reading and accurate clapping.",
    requiredResources: "Set of rhythm flashcards (printable).",
    youtubeLink: "",
    externalLink: "",
    activityType: "Rhythm",
    difficulty: "Beginner",
    term: "Autumn 1",
    tags: ["rhythm reading", "ta", "ti-ti"],
  },
  {
    title: "Pentatonic Improvisation Circle",
    ageRange: "8-11",
    keyStage: "KS2",
    kodalyFocus: "Pentatonic improvisation",
    rhythmElement: "ta, ti-ti, tika-tika",
    solfaElement: "do, re, mi, so, la",
    curriculumLink: "NC Music KS2: Improvise and compose music",
    description: "Children take turns improvising a 4-beat melody on pentatonic tuned percussion.",
    instructions: "Set up pentatonic xylophones (remove F and B). One child plays a 4-beat answer to a teacher question. Class echoes if desired.",
    questions: "Did your phrase end on do? Which notes felt restful?",
    assessmentFocus: "Confidence in improvisation; phrase shape.",
    requiredResources: "Pentatonic-set tuned percussion.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Composition",
    difficulty: "Intermediate",
    term: "Spring 1",
    tags: ["pentatonic", "improvisation"],
  },
  {
    title: "Tika-tika Dictation",
    ageRange: "8-10",
    keyStage: "KS2",
    kodalyFocus: "Semiquavers (tika-tika)",
    rhythmElement: "tika-tika, ta, ti-ti",
    solfaElement: "",
    curriculumLink: "NC Music KS2: Use and understand staff and other musical notations",
    description: "Teacher claps 4-beat patterns including tika-tika; pupils notate.",
    instructions: "Clap a 4-beat pattern twice. Pupils notate using stick notation. Reveal the answer and discuss.",
    questions: "How many sounds on beat 1? Where did the four-sound pattern fall?",
    assessmentFocus: "Rhythm dictation accuracy.",
    requiredResources: "Whiteboards or rhythm grids.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Dictation",
    difficulty: "Intermediate",
    term: "Spring 2",
    tags: ["dictation", "tika-tika"],
  },
  {
    title: "Two-part Round: 'Frère Jacques'",
    ageRange: "8-11",
    keyStage: "KS2",
    kodalyFocus: "Part work in canon",
    rhythmElement: "ta, ti-ti",
    solfaElement: "do-re-mi-fa-so",
    curriculumLink: "NC Music KS2: Sing in solo and in ensemble contexts",
    description: "Sing in two parts as a canon, entering at bar 3.",
    instructions: "Teach the song unison first. Split into two groups; group B starts when group A reaches bar 3. Listen for tuning at the unison points.",
    questions: "Can you stay on your part when the other group enters?",
    assessmentFocus: "Independence in part-singing; tuning.",
    requiredResources: "None.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Singing",
    difficulty: "Intermediate",
    term: "Summer 1",
    tags: ["canon", "part work"],
  },
  {
    title: "Compound Time Body Percussion",
    ageRange: "11-14",
    keyStage: "KS3",
    kodalyFocus: "6/8 compound time",
    rhythmElement: "Compound time",
    solfaElement: "",
    curriculumLink: "NC Music KS3: Develop a deepening understanding of musical elements",
    description: "Layered body percussion ostinati in 6/8.",
    instructions: "Group A: stomp dotted crotchets. Group B: clap quavers. Group C: pat 'long-short' patterns. Layer in turns.",
    questions: "How many quavers per beat? How does compound feel different from simple?",
    assessmentFocus: "Maintaining independent parts in compound time.",
    requiredResources: "None.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Rhythm",
    difficulty: "Intermediate",
    term: "Autumn 2",
    tags: ["6/8", "body percussion"],
  },
  {
    title: "Modal Improvisation: Dorian",
    ageRange: "13-16",
    keyStage: "KS4",
    kodalyFocus: "Modal improvisation",
    rhythmElement: "Free",
    solfaElement: "Dorian (re-based)",
    curriculumLink: "GCSE-style: Composing in different styles and traditions",
    description: "Improvise melodies over a D-Dorian drone.",
    instructions: "Hold a D drone (D + A). Pupils improvise on D-E-F-G-A-B-C-D scale, focusing on the raised 6th (B natural) as the modal colour.",
    questions: "Which note gives the Dorian flavour? How does ending on D feel?",
    assessmentFocus: "Modal awareness; phrase construction.",
    requiredResources: "Keyboard or drone track.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Composition",
    difficulty: "Advanced",
    term: "Spring 1",
    tags: ["modes", "dorian"],
  },
  {
    title: "Listening: 'In the Hall of the Mountain King'",
    ageRange: "7-11",
    keyStage: "KS2",
    kodalyFocus: "Tempo, dynamics, ostinato",
    rhythmElement: "Steady ostinato",
    solfaElement: "",
    curriculumLink: "NC Music KS2: Appreciate and understand a wide range of high-quality live and recorded music",
    description: "Active listening to Grieg's piece, tracking the ostinato.",
    instructions: "Children walk in pulse on the ostinato, speed up with the music, freeze on accents. Discuss tempo and dynamics afterwards.",
    questions: "What happens to the speed? How loud does it get?",
    assessmentFocus: "Active listening; describing musical change.",
    requiredResources: "Audio of 'In the Hall of the Mountain King'.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Listening",
    difficulty: "Beginner",
    term: "Spring 2",
    tags: ["listening", "tempo", "ostinato"],
  },
  {
    title: "Beat Grid: Compose a 4-beat Pattern",
    ageRange: "6-9",
    keyStage: "KS1",
    kodalyFocus: "Rhythm composition",
    rhythmElement: "ta, ti-ti, rest",
    solfaElement: "",
    curriculumLink: "NC Music KS1: Experiment with, create, select and combine sounds",
    description: "Pupils compose a 4-beat rhythm by filling a grid.",
    instructions: "Provide a 4-cell grid. Pupils choose ta, ti-ti or rest for each cell. They clap their pattern; partner echoes.",
    questions: "Which beat has two sounds? Can you teach your partner?",
    assessmentFocus: "Rhythm composition and notation.",
    requiredResources: "Beat grid worksheets.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Composition",
    difficulty: "Beginner",
    term: "Spring 1",
    tags: ["beat grid", "composition"],
  },
  {
    title: "Hand Sign Echo",
    ageRange: "5-9",
    keyStage: "KS1",
    kodalyFocus: "Hand signs",
    rhythmElement: "",
    solfaElement: "do, mi, so, la",
    curriculumLink: "NC Music KS1: Listen with concentration and understanding",
    description: "Teacher shows hand signs; pupils sing back the pattern.",
    instructions: "Stand in a circle. Teacher shows a 4-note pattern with hand signs. Pupils sing back using solfa. Increase length each turn.",
    questions: "Can you remember 6 notes? Which note is so?",
    assessmentFocus: "Pitch memory and hand sign recognition.",
    requiredResources: "None.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Solfa",
    difficulty: "Beginner",
    term: "Autumn 2",
    tags: ["hand signs", "echo"],
  },
  {
    title: "EYFS: Sound Story 'The Storm'",
    ageRange: "3-5",
    keyStage: "EYFS",
    kodalyFocus: "Sound exploration, dynamics",
    rhythmElement: "Free",
    solfaElement: "",
    curriculumLink: "EYFS EAD: Explore, use and refine a variety of artistic effects",
    description: "Children create a soundscape of a storm using bodies and instruments.",
    instructions: "Tell a storm story. At each stage, children make matching sounds: rain (finger taps), thunder (drums), wind (whoosh voices). End with calm.",
    questions: "How will we make the rain sound? Loud or quiet at the start?",
    assessmentFocus: "Sound choice and dynamic control.",
    requiredResources: "Untuned percussion.",
    youtubeLink: "",
    externalLink: "",
    activityType: "Composition",
    difficulty: "Beginner",
    term: "Autumn 2",
    tags: ["soundscape", "EYFS"],
  },
];

// Singing-game activities sourced from Mr. Meehl's Music YouTube channel
// (https://www.youtube.com/@MrMeehlsMusic). Each YouTube link below was confirmed
// against that channel's public video listing. Songs are traditional folk pieces
// long used in the Kodály method — well-suited as classroom singing games.
const MEEHL_ACTIVITIES = [
  {
    title: "Apples & Bananas",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "Vowel substitution, diction",
    rhythmElement: "ta, ti-ti", solfaElement: "do-re-mi-fa-so",
    curriculumLink: "NC Music KS1: Use voices expressively, sing songs and chants",
    description: "Vowel-play song where each verse swaps the vowels — fantastic for diction, memory and silly singing fun.",
    instructions: "Sing the original verse, then verse-by-verse replace every vowel with A, then E, then I, then O, then U. Pat the steady beat throughout.",
    questions: "Which vowel was hardest? What changes about the words but not the tune?",
    assessmentFocus: "Pitch retention while words change.",
    requiredResources: "None (optional: vowel cards).",
    youtubeLink: "https://www.youtube.com/watch?v=IrRxnhuxCpY",
    externalLink: "", activityType: "Singing", difficulty: "Beginner", term: "Autumn 1",
    tags: ["folk song", "diction", "vowels"],
  },
  {
    title: "Bickle Bockle",
    ageRange: "5-7", keyStage: "KS1",
    kodalyFocus: "Steady pulse, so-mi-la",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Use voices expressively, sing songs and chants",
    description: "Short circle game with a clear so-mi-la melodic frame — quick to learn and ideal for a warm-up.",
    instructions: "Sit in a circle with one child as the chooser. Sing 'Bickle Bockle' tapping pulse on knees; the chooser taps a hand on each beat and the child tapped on the final beat takes the next turn.",
    questions: "Where is the highest note? Can you keep the pulse with your knees?",
    assessmentFocus: "Pulse-keeping; pitch matching of so-mi-la.",
    requiredResources: "None — circle game.",
    youtubeLink: "https://www.youtube.com/watch?v=z040-PTczUQ",
    externalLink: "", activityType: "Singing Game", difficulty: "Beginner", term: "Autumn 1",
    tags: ["circle game", "so-mi-la", "pulse"],
  },
  {
    title: "Black Snake",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "Steady beat, line game",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Play tuned and untuned instruments musically",
    description: "Movement song where the line of children winds like a snake — great for beat-keeping with locomotion.",
    instructions: "Children form a line holding shoulders. Walk to the pulse while singing. The leader winds the 'snake' around the room, then under arches.",
    questions: "What does your body do on the beat?",
    assessmentFocus: "Walking in time; group cooperation.",
    requiredResources: "Open space.",
    youtubeLink: "https://www.youtube.com/watch?v=-ufd61VQSJA",
    externalLink: "", activityType: "Singing Game", difficulty: "Beginner", term: "Autumn 2",
    tags: ["line game", "movement"],
  },
  {
    title: "Can You Guess Who Has the Ring",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "Inner hearing, listening focus",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Listen with concentration and understanding",
    description: "Guessing-circle game that develops inner hearing and observation.",
    instructions: "One child closes eyes in the centre. The class passes a ring while singing. On the final beat the music stops; the child in the middle guesses who hides the ring.",
    questions: "Did you keep the song going in your head when you weren't singing?",
    assessmentFocus: "Active listening; inner hearing.",
    requiredResources: "A small ring or object.",
    youtubeLink: "https://www.youtube.com/watch?v=HStgMKL5Z0g",
    externalLink: "", activityType: "Singing Game", difficulty: "Beginner", term: "Spring 1",
    tags: ["inner hearing", "guessing game"],
  },
  {
    title: "Chicken On a Fencepost",
    ageRange: "6-9", keyStage: "KS1",
    kodalyFocus: "Pentatonic melody, square-dance feel",
    rhythmElement: "ta, ti-ti", solfaElement: "do-re-mi-so-la",
    curriculumLink: "NC Music KS1: Use voices expressively, sing songs and chants",
    description: "Bouncy American folk song with a pentatonic tune — perfect for a partner-swap dance.",
    instructions: "Pairs face each other in a circle. Sing the verse swinging right-elbow then left-elbow. On the final phrase pairs side-step on to a new partner.",
    questions: "Which scale notes are missing? (fa and ti)",
    assessmentFocus: "Pentatonic singing in tune; partner coordination.",
    requiredResources: "Open space.",
    youtubeLink: "https://www.youtube.com/watch?v=Y5129ROMIHg",
    externalLink: "", activityType: "Singing Game", difficulty: "Beginner", term: "Autumn 2",
    tags: ["pentatonic", "partner game"],
  },
  {
    title: "Clementine",
    ageRange: "7-11", keyStage: "KS2",
    kodalyFocus: "Triple metre (3/4), diatonic melody",
    rhythmElement: "ta, ti-ti, dotted patterns", solfaElement: "Full diatonic",
    curriculumLink: "NC Music KS2: Sing in solo and in ensemble contexts",
    description: "Classic American ballad in 3/4 — great for introducing waltz feel and verse/chorus form.",
    instructions: "Sing in unison swaying on beats 1-2-3. Add a clap on beat 1 to feel the metre. Discuss the AABA verse–chorus structure.",
    questions: "How many beats in a bar? Can you hear the difference between the verse and chorus?",
    assessmentFocus: "Triple-metre feel; phrase shape.",
    requiredResources: "Lyric sheet (optional).",
    youtubeLink: "https://www.youtube.com/watch?v=rOQnL0WZOiU",
    externalLink: "", activityType: "Singing", difficulty: "Intermediate", term: "Spring 1",
    tags: ["folk song", "3/4", "ballad"],
  },
  {
    title: "Closet Key",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "so-mi-la pentatonic; ear training",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la-do",
    curriculumLink: "NC Music KS1: Listen with concentration and understanding",
    description: "Sit-down circle game where a 'key' is hidden behind a child while everyone sings.",
    instructions: "Children sit in a circle, eyes closed. One child has the 'key' (a small object) and places it behind a chosen friend. Everyone sings; on the last beat the chosen child opens their eyes.",
    questions: "Was the song the same speed each time?",
    assessmentFocus: "Pulse-keeping with eyes closed; group singing.",
    requiredResources: "A small 'key' object.",
    youtubeLink: "https://www.youtube.com/watch?v=E17qoDA2j2Q",
    externalLink: "", activityType: "Singing Game", difficulty: "Beginner", term: "Autumn 1",
    tags: ["circle game", "so-mi-la"],
  },
  {
    title: "Cut the Cake",
    ageRange: "5-7", keyStage: "KS1",
    kodalyFocus: "Steady beat, simple line game",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Use voices expressively, sing songs and chants",
    description: "Short song where children 'cut' the line in two — a great way to introduce ensemble division.",
    instructions: "Class stands in a line holding hands and singing. The leader walks down the line and 'cuts' between two children on the final word; the line becomes two groups for the next round.",
    questions: "How many groups are there now? Can each group still keep the beat?",
    assessmentFocus: "Maintaining pulse during group changes.",
    requiredResources: "Open space.",
    youtubeLink: "https://www.youtube.com/watch?v=40ACIdWd-54",
    externalLink: "", activityType: "Singing Game", difficulty: "Beginner", term: "Autumn 2",
    tags: ["line game", "groupwork"],
  },
  {
    title: "Ebeneezer Sneezer",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "Vocal exploration, sirens",
    rhythmElement: "Free", solfaElement: "Vocal slides (high/low)",
    curriculumLink: "NC Music KS1: Use their voices expressively and creatively",
    description: "Silly chant for vocal warm-up — explore the full range of the voice with sirens and 'sneezes'.",
    instructions: "Chant the rhyme together. On 'sneeze' make a big high-to-low siren. Add staircase hand gestures matching the voice direction.",
    questions: "Can your voice slide higher than last time?",
    assessmentFocus: "Vocal range exploration; pitch direction.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=8DoN7HfUTXQ",
    externalLink: "", activityType: "Singing", difficulty: "Beginner", term: "Autumn 1",
    tags: ["warm-up", "vocal exploration"],
  },
  {
    title: "Fooba Wooba",
    ageRange: "7-11", keyStage: "KS2",
    kodalyFocus: "Compound feel; nonsense-word memory",
    rhythmElement: "Skipping rhythm (6/8 feel)", solfaElement: "do-re-mi-so-la",
    curriculumLink: "NC Music KS2: Sing in solo and in ensemble contexts",
    description: "Energetic American nonsense song that lifts the room — superb for compound metre and memory.",
    instructions: "Teach the chorus by call-and-response. Add a knee-pat on beat 1 and clap on beat 2 to feel the lilt. Add new verses each lesson.",
    questions: "How many main pulses in each bar? What word always comes on the strong beat?",
    assessmentFocus: "Compound-time feel; lyric memory.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=k_St5cwjcXs",
    externalLink: "https://www.youtube.com/watch?v=HY1lph5y1bM",
    activityType: "Singing", difficulty: "Intermediate", term: "Spring 2",
    tags: ["compound time", "nonsense song"],
  },
  {
    title: "Frog In the Meadow",
    ageRange: "7-10", keyStage: "KS2",
    kodalyFocus: "Pentatonic singing game; do-pentatonic",
    rhythmElement: "ta, ti-ti", solfaElement: "do-re-mi-so-la",
    curriculumLink: "NC Music KS2: Play and perform in ensemble contexts",
    description: "Traditional pentatonic game with a chasing element — already named in the KS2 Singing Games strand.",
    instructions: "One child is the 'frog' inside a circle. Class sings while walking the beat. On the final word the frog hops to a new child who becomes the next frog.",
    questions: "Which note feels like 'home'? (do)",
    assessmentFocus: "Pentatonic intonation; pulse on the move.",
    requiredResources: "Open space.",
    youtubeLink: "https://www.youtube.com/watch?v=SeHew3YyKX4",
    externalLink: "https://www.youtube.com/watch?v=GNaPcOd0iAk",
    activityType: "Singing Game", difficulty: "Intermediate", term: "Autumn 2",
    tags: ["pentatonic", "chasing game"],
  },
  {
    title: "Going Over the Sea",
    ageRange: "7-11", keyStage: "KS2",
    kodalyFocus: "Cumulative number song; beat in 6/8",
    rhythmElement: "Compound (6/8)", solfaElement: "do-re-mi-fa-so",
    curriculumLink: "NC Music KS2: Listen with attention to detail and recall sounds",
    description: "Cumulative number song — verses add an action with each new number. Excellent for memory and 6/8 lilt.",
    instructions: "Sing verses 1-10, adding a new action each verse (e.g. 'when I was one… I sucked my thumb'). Keep the swing of the 6/8 beat throughout.",
    questions: "How many beats in a bar? Can you remember every action?",
    assessmentFocus: "Cumulative memory; 6/8 swing.",
    requiredResources: "Action prompts (optional).",
    youtubeLink: "https://www.youtube.com/watch?v=_S40Lv0zwuw",
    externalLink: "", activityType: "Singing", difficulty: "Intermediate", term: "Spring 1",
    tags: ["6/8", "cumulative", "memory"],
  },
  {
    title: "KITTY (K-I-T-T-Y)",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "Spelling, steady beat",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Play tuned and untuned instruments musically",
    description: "Letter-spelling chant — pulse-keeping with literacy crossover.",
    instructions: "Class chants 'K-I-T-T-Y spells Kitty' clapping on each letter. Try removing a letter each round (sing it inside your head).",
    questions: "How many beats are there? Can you keep singing in your head when we drop a letter?",
    assessmentFocus: "Pulse with omission; inner hearing.",
    requiredResources: "Letter cards (optional).",
    youtubeLink: "https://www.youtube.com/watch?v=qCVkalLYQ0g",
    externalLink: "", activityType: "Rhythm", difficulty: "Beginner", term: "Autumn 2",
    tags: ["spelling", "inner hearing"],
  },
  {
    title: "Mouse Mousie",
    ageRange: "5-7", keyStage: "KS1",
    kodalyFocus: "Quiet singing; suspense",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Use their voices expressively and creatively",
    description: "Tip-toe game where the class sings quietly so as 'not to wake the cat'.",
    instructions: "One child is the cat, head down. The 'mouse' tip-toes around the circle while everyone sings quietly. On the final word the cat looks up and tries to guess who the mouse is.",
    questions: "How quiet can we be without losing the tune?",
    assessmentFocus: "Dynamic control; pitch at low volume.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=Rv3V64DuVCU",
    externalLink: "", activityType: "Singing Game", difficulty: "Beginner", term: "Spring 1",
    tags: ["dynamics", "circle game"],
  },
  {
    title: "Oh Chester",
    ageRange: "5-9", keyStage: "KS1",
    kodalyFocus: "Body parts; coordination",
    rhythmElement: "ta, ti-ti", solfaElement: "do-re-mi-so",
    curriculumLink: "NC Music KS1: Listen with concentration and understanding",
    description: "Action song where children touch a different body part on each beat — focus and pulse.",
    instructions: "Sing 'Oh Chester' adding touches: chest, head, shoulder, knee, etc. Each verse swap one word for a silent gesture. Keep accelerating.",
    questions: "Which beat had the silent word?",
    assessmentFocus: "Coordination; pulse with substitution.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=rSZd7iZf1Vs",
    externalLink: "", activityType: "Singing", difficulty: "Beginner", term: "Autumn 1",
    tags: ["action song", "coordination"],
  },
  {
    title: "Old Mister Rabbit",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "so-mi-la-do; story singing",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la-do",
    curriculumLink: "NC Music KS1: Use voices expressively, sing songs and chants",
    description: "Cheerful story-song in pentatonic — quick to teach by rote.",
    instructions: "Teach the song by call-and-response. Add a hop on the word 'Rabbit' each time. Optionally let one child act as Mr Rabbit.",
    questions: "Can you sing the next phrase before I do?",
    assessmentFocus: "Memory; pentatonic intonation.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=ogzMA7f3zkY",
    externalLink: "https://www.youtube.com/watch?v=Ym_q33vJVSQ",
    activityType: "Singing Game", difficulty: "Beginner", term: "Autumn 2",
    tags: ["pentatonic", "story song"],
  },
  {
    title: "Pizza Man",
    ageRange: "5-8", keyStage: "KS1",
    kodalyFocus: "Steady beat; food-themed singing",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Use voices expressively, sing songs and chants",
    description: "Cheerful steady-beat song easy to learn and great as a transition song.",
    instructions: "Pat the pulse on knees. Sing the verse adding a topping each round (children call out their favourite).",
    questions: "What is the difference between beat and rhythm in this song?",
    assessmentFocus: "Pulse-keeping; word substitution memory.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=v33gHZb1IMI",
    externalLink: "", activityType: "Singing", difficulty: "Beginner", term: "Autumn 1",
    tags: ["transition", "pulse"],
  },
  {
    title: "Plainsies Clapsies",
    ageRange: "6-9", keyStage: "KS1",
    kodalyFocus: "Hand-clapping game; coordination",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "NC Music KS1: Play tuned and untuned instruments musically",
    description: "Traditional ball-bouncing or hand-clapping game with cumulative actions.",
    instructions: "Pairs face each other. Each verse adds a new clap pattern (Plainsies, then Clapsies, then Backsies…). Keep the pulse steady throughout.",
    questions: "Can you keep going if I add another action?",
    assessmentFocus: "Cumulative motor skills; pulse with rising complexity.",
    requiredResources: "None (optional: a small ball).",
    youtubeLink: "https://www.youtube.com/watch?v=2zNLUEyZCo8",
    externalLink: "", activityType: "Rhythm", difficulty: "Intermediate", term: "Spring 2",
    tags: ["clapping game", "coordination"],
  },
  {
    title: "Pull the Anchor",
    ageRange: "7-11", keyStage: "KS2",
    kodalyFocus: "Sea shanty; call-and-response",
    rhythmElement: "Strong beat 1; pulling rhythm", solfaElement: "do-re-mi-so",
    curriculumLink: "NC Music KS2: Sing in solo and in ensemble contexts",
    description: "Sea-shanty style work song — children 'pull' on the strong beats.",
    instructions: "Form two lines holding an imaginary rope. Leader sings the call; class sings the response and pulls firmly on the strong beats.",
    questions: "Which beat do we pull on? Why does that help the work?",
    assessmentFocus: "Strong-beat awareness; ensemble timing.",
    requiredResources: "None (optional: long rope or scarf).",
    youtubeLink: "https://www.youtube.com/watch?v=1TJglI1IWZU",
    externalLink: "", activityType: "Singing", difficulty: "Intermediate", term: "Summer 1",
    tags: ["shanty", "call and response"],
  },
  {
    title: "Rattlin' Bog",
    ageRange: "8-11", keyStage: "KS2",
    kodalyFocus: "Cumulative song; memory; tempo control",
    rhythmElement: "ta, ti-ti", solfaElement: "do-re-mi-fa-so",
    curriculumLink: "NC Music KS2: Listen with attention to detail and recall sounds",
    description: "Famous Irish cumulative song — verses add a new noun and the chorus repeats them all in reverse. Brilliant for memory.",
    instructions: "Teach verse-by-verse. Each verse adds one item: tree → branch → twig → nest → egg → bird → feather. Repeat the chorus list in reverse, accelerating.",
    questions: "What helps you remember the order?",
    assessmentFocus: "Cumulative memory; ensemble at speed.",
    requiredResources: "Picture cards in order (optional).",
    youtubeLink: "https://www.youtube.com/watch?v=XqN3YB41fxo",
    externalLink: "", activityType: "Singing", difficulty: "Intermediate", term: "Spring 2",
    tags: ["cumulative", "irish folk", "memory"],
  },
  {
    title: "Six Little Ducks",
    ageRange: "3-6", keyStage: "EYFS",
    kodalyFocus: "Pulse, action song",
    rhythmElement: "ta, ti-ti", solfaElement: "so-mi-la",
    curriculumLink: "EYFS EAD: Sing a range of well-known nursery rhymes and songs",
    description: "EYFS staple action song — a perfect 'whole class up and moving' moment.",
    instructions: "Children waddle in a line behind a leader 'duck'. Sing the verse adding wing-flap and quack actions. Swap leaders each verse.",
    questions: "Can you stay in time with the leader?",
    assessmentFocus: "Following the beat in motion.",
    requiredResources: "Open space.",
    youtubeLink: "https://www.youtube.com/watch?v=fmMUc2_XnvQ",
    externalLink: "https://www.youtube.com/watch?v=d4ps1EXtXJM",
    activityType: "Singing Game", difficulty: "Beginner", term: "Autumn 1",
    tags: ["EYFS", "action song"],
  },
  {
    title: "The More We Get Together",
    ageRange: "4-7", keyStage: "EYFS",
    kodalyFocus: "Ensemble singing; community",
    rhythmElement: "Triple feel (3/4)", solfaElement: "do-re-mi-fa-so-la",
    curriculumLink: "EYFS EAD: Perform songs, rhymes, poems and stories with others",
    description: "Friendly opening or closing song — great for gathering circles or assemblies.",
    instructions: "Stand in a circle holding hands, swing on beats 1-2-3. On 'your friends are my friends' point to a partner across the circle.",
    questions: "How does our class sound when we all sing together?",
    assessmentFocus: "Ensemble unison; triple-metre swing.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=Xrw-CzMO-U0",
    externalLink: "", activityType: "Singing", difficulty: "Beginner", term: "Autumn 1",
    tags: ["3/4", "circle song", "EYFS"],
  },
  {
    title: "There's A Hole In the Bottom Of the Sea",
    ageRange: "6-10", keyStage: "KS2",
    kodalyFocus: "Cumulative song; memory; phrase building",
    rhythmElement: "ta, ti-ti", solfaElement: "do-re-mi-so",
    curriculumLink: "NC Music KS2: Listen with attention to detail and recall sounds",
    description: "Cumulative song where each verse adds a new creature — a great memory builder.",
    instructions: "Teach verse 1 (hole). Each verse add: log → bump → frog → fly → wing → flea. Use ocean-themed actions for each creature.",
    questions: "What strategy helps you remember? Picture, action, or word?",
    assessmentFocus: "Memory; phrase recall under accumulation.",
    requiredResources: "Picture sequence cards (optional).",
    youtubeLink: "https://www.youtube.com/watch?v=8jKfBvo2LTM",
    externalLink: "", activityType: "Singing", difficulty: "Intermediate", term: "Summer 1",
    tags: ["cumulative", "memory"],
  },
  {
    title: "Throw It Out the Window",
    ageRange: "6-10", keyStage: "KS2",
    kodalyFocus: "Familiar tune mash-up; humour",
    rhythmElement: "ta, ti-ti", solfaElement: "Full diatonic",
    curriculumLink: "NC Music KS2: Sing in solo and in ensemble contexts",
    description: "Silly singing game where the last line of every nursery rhyme is replaced with 'and threw it out the window'.",
    instructions: "Class sings well-known nursery rhymes (Mary Had a Little Lamb, Hickory Dickory Dock…). Replace the final line with 'and threw it out the window'. Add 'crash!' actions.",
    questions: "Which nursery rhyme fitted best?",
    assessmentFocus: "Memory of melody when words change.",
    requiredResources: "Nursery-rhyme prompts (optional).",
    youtubeLink: "https://www.youtube.com/watch?v=L__wMBgMdo0",
    externalLink: "", activityType: "Singing", difficulty: "Beginner", term: "Spring 1",
    tags: ["nursery rhyme", "humour"],
  },
  {
    title: "Tick Tock",
    ageRange: "4-7", keyStage: "EYFS",
    kodalyFocus: "Steady beat; tempo contrast",
    rhythmElement: "Steady pulse", solfaElement: "so-mi",
    curriculumLink: "EYFS EAD: Listen attentively, move to and talk about music",
    description: "Clock-themed song with built-in tempo changes — a memorable way to introduce fast/slow.",
    instructions: "Sway like a pendulum on each beat. Sing the verse slowly first ('grandfather clock'), then medium ('wall clock'), then fast ('cuckoo clock').",
    questions: "Which clock was fastest? How did your body show the speed?",
    assessmentFocus: "Tempo recognition and reproduction.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=Q2tFAlL61l0",
    externalLink: "", activityType: "Rhythm", difficulty: "Beginner", term: "Autumn 1",
    tags: ["tempo", "EYFS"],
  },
  {
    title: "Tideo",
    ageRange: "7-11", keyStage: "KS2",
    kodalyFocus: "Pentatonic singing game; circle dance",
    rhythmElement: "ta, ti-ti, ta-rest", solfaElement: "do-re-mi-so-la",
    curriculumLink: "NC Music KS2: Play and perform in ensemble contexts",
    description: "Lively American singing game with a window-pass move — Kodály-method classic at KS2.",
    instructions: "Form a circle with one extra child outside. Sing the verse stamping the pulse. On 'pass one window', the outside child weaves under raised arms. Swap on each chorus.",
    questions: "Where is the rest? What note is 'home' (do)?",
    assessmentFocus: "Pulse, weaving timing, pentatonic intonation.",
    requiredResources: "Open space.",
    youtubeLink: "https://www.youtube.com/watch?v=feBgMaqw7gM",
    externalLink: "", activityType: "Singing Game", difficulty: "Intermediate", term: "Spring 2",
    tags: ["pentatonic", "circle game"],
  },
  {
    title: "Toembai",
    ageRange: "9-13", keyStage: "KS2",
    kodalyFocus: "Two-part round; ensemble singing",
    rhythmElement: "Steady ta, ti-ti", solfaElement: "do-mi-so (chord I)",
    curriculumLink: "NC Music KS2: Sing in solo and in ensemble contexts",
    description: "Beautiful three-part round in a minor mode — a wonderful introduction to part singing.",
    instructions: "Teach in unison until secure. Split into two then three groups; group 2 enters at the second phrase, group 3 at the third. Sing in a circle for tuning.",
    questions: "Can you stay on your part when the other group enters?",
    assessmentFocus: "Independence in part singing; intonation in minor.",
    requiredResources: "None.",
    youtubeLink: "https://www.youtube.com/watch?v=H6tPT0i3NFw",
    externalLink: "", activityType: "Singing", difficulty: "Advanced", term: "Summer 2",
    tags: ["round", "part singing", "minor"],
  },
  {
    title: "Weevily Wheat",
    ageRange: "7-11", keyStage: "KS2",
    kodalyFocus: "Appalachian folk; partner dance",
    rhythmElement: "Skipping (6/8)", solfaElement: "do-re-mi-so-la",
    curriculumLink: "NC Music KS2: Appreciate and understand a wide range of high-quality live and recorded music",
    description: "Lively Appalachian play-party song with a partner-dance — perfect for KS2 ensemble singing and movement.",
    instructions: "Pairs hold hands across the circle. On the verse swing partners. On the chorus all promenade in 6/8. Encourage clear diction at speed.",
    questions: "What gives this song its 'skipping' feel?",
    assessmentFocus: "Compound feel in motion; partner work.",
    requiredResources: "Open space.",
    youtubeLink: "https://www.youtube.com/watch?v=Q-LLZ9u7WAw",
    externalLink: "https://www.youtube.com/watch?v=Bll5rUkyWP0",
    activityType: "Singing Game", difficulty: "Intermediate", term: "Summer 1",
    tags: ["appalachian", "6/8", "partner dance"],
  },
];

const DEFAULT_CURRICULUM_LINKS = [
  { keyStage: "EYFS", framework: "EYFS EAD", objective: "Sing a range of well-known nursery rhymes and songs", skillArea: "Singing" },
  { keyStage: "EYFS", framework: "EYFS EAD", objective: "Perform songs, rhymes, poems and stories with others", skillArea: "Performing" },
  { keyStage: "EYFS", framework: "EYFS EAD", objective: "Listen attentively, move to and talk about music", skillArea: "Listening" },
  { keyStage: "KS1", framework: "NC Music KS1", objective: "Use their voices expressively and creatively by singing songs and speaking chants and rhymes", skillArea: "Singing" },
  { keyStage: "KS1", framework: "NC Music KS1", objective: "Play tuned and untuned instruments musically", skillArea: "Performing" },
  { keyStage: "KS1", framework: "NC Music KS1", objective: "Listen with concentration and understanding to a range of high-quality live and recorded music", skillArea: "Listening" },
  { keyStage: "KS1", framework: "NC Music KS1", objective: "Experiment with, create, select and combine sounds using the inter-related dimensions of music", skillArea: "Composing" },
  { keyStage: "KS2", framework: "NC Music KS2", objective: "Play and perform in solo and ensemble contexts, using their voices and playing musical instruments with increasing accuracy, fluency, control and expression", skillArea: "Performing" },
  { keyStage: "KS2", framework: "NC Music KS2", objective: "Improvise and compose music for a range of purposes using the inter-related dimensions of music", skillArea: "Composing" },
  { keyStage: "KS2", framework: "NC Music KS2", objective: "Listen with attention to detail and recall sounds with increasing aural memory", skillArea: "Listening" },
  { keyStage: "KS2", framework: "NC Music KS2", objective: "Use and understand staff and other musical notations", skillArea: "Notation" },
  { keyStage: "KS2", framework: "NC Music KS2", objective: "Appreciate and understand a wide range of high-quality live and recorded music drawn from different traditions", skillArea: "Appraising" },
  { keyStage: "KS2", framework: "NC Music KS2", objective: "Develop an understanding of the history of music", skillArea: "Appraising" },
  { keyStage: "KS3", framework: "NC Music KS3", objective: "Play and perform confidently in a range of solo and ensemble contexts using their voice, playing instruments musically, fluently and with accuracy and expression", skillArea: "Performing" },
  { keyStage: "KS3", framework: "NC Music KS3", objective: "Improvise and compose; and extend and develop musical ideas by drawing on a range of musical structures, styles, genres and traditions", skillArea: "Composing" },
  { keyStage: "KS3", framework: "NC Music KS3", objective: "Use staff and other relevant notations appropriately and accurately in a range of musical styles, genres and traditions", skillArea: "Notation" },
  { keyStage: "KS3", framework: "NC Music KS3", objective: "Identify and use the inter-related dimensions of music expressively and with increasing sophistication", skillArea: "Appraising" },
  { keyStage: "KS3", framework: "NC Music KS3", objective: "Listen with increasing discrimination to a wide range of music from great composers and musicians", skillArea: "Listening" },
  { keyStage: "KS4", framework: "GCSE-style", objective: "Perform as a soloist and as part of an ensemble", skillArea: "Performing" },
  { keyStage: "KS4", framework: "GCSE-style", objective: "Compose music that uses musical elements, devices, conventions and structures", skillArea: "Composing" },
  { keyStage: "KS4", framework: "GCSE-style", objective: "Appraise and analyse music using musical vocabulary", skillArea: "Appraising" },
];
